algoritmo "Soma de tres numeros"

var
   n1, n2, n3, resultado: real

inicio
// Seção de Comandos 
   escreva ("Digite o primeiro numero da soma: ")
   leia (n1)
   escreva ("Digite o segundo numero da soma: ")
   leia (n2)
   escreva ("Digite o terceiro numero da soma: ")
   leia (n3)
   //soma e apresentar o resultado
   resultado<- n1 + n2 + n3
   limpatela
   escreva ("A soma dos tres numeros apresentados resulta em: ", resultado)
   
fimalgoritmo
